---
- name: change hostname1 file
  replace: dest=/etc/hosts
           regexp="{{item.regexp}}"
           replace="{{item.replace}}"
  with_items:
    - { regexp: '^127.0.1.1', replace: '10.0.1.1' }
    - { regexp: 'ubuntu', replace: 'node1' } 
  when: inventory_hostname == '10.0.1.1'


- name: set hostname1
  hostname: 
    name: node1
  when: inventory_hostname == '10.0.1.1'


- name: change hostname2 file
  replace: dest=/etc/hosts
           regexp="{{item.regexp}}"
           replace="{{item.replace}}"
  with_items:
    - { regexp: '^127.0.1.1', replace: '10.0.2.1' }
    - { regexp: 'ubuntu', replace: 'node2' }
  when: inventory_hostname == '10.0.2.1'


- name: set hostname2
  hostname: 
    name: node2
  when: inventory_hostname == '10.0.2.1'
