---
- name: install nova-compute component
  apt:
    name:
      - nova-compute
      - nova-compute-kvm
      - qemu-system-data
      - apache2


- name: nova.confのstatusを取得
  stat: path=/etc/nova/nova.conf
  register: nova_conf_stat


- name: nova config backup
  command: mv /etc/nova/nova.conf /etc/nova/nova.conf.org
  when: nova_conf_stat.stat.exists


- name: copy files
  copy:
    src: ~/openstackope/roles/openstackHV/tasks/nova.conf 
    dest: /etc/nova/


- name: compile nova.conf for main
  replace: dest=/etc/nova/nova.conf
           regexp="{{item.regexp}}"
           replace="{{item.replace}}"
  with_items:
    - { regexp: '^my_ip = 7.1.10.1', replace: 'my_ip = 10.0.1.1' }
    - { regexp: '^server_proxyclient_address = 7.1.10.1', replace: 'server_proxyclient_address = 10.0.1.1' }
    - { regexp: '^http://7.1.10.1:6080/vnc_auto.html', replace: 'http://10.0.1.1:6080/vnc_auto.html ' }
  when: inventory_hostname == '10.0.1.1'


- name: compile nova.conf for backup
  replace: dest=/etc/nova/nova.conf
           regexp="{{item.regexp}}"
           replace="{{item.replace}}"
  with_items:
    - { regexp: '^my_ip = 7.1.10.1', replace: 'my_ip = 10.0.2.1' }
    - { regexp: '^server_proxyclient_address = 7.1.10.1', replace: 'server_proxyclient_address = 10.0.2.1' }
    - { regexp: '^http://7.1.10.1:6080/vnc_auto.html', replace: 'http://10.0.2.1:6080/vnc_auto.html ' }
  when: inventory_hostname == '10.0.2.1'

- name: change access auth
  file:
    path: /etc/nova/nova.conf
    mode: 0640
    group: nova
