---
- name: install needed software
  apt:
    name:
      - software-properties-common 


- name: check victoria repository
  command: ls /etc/apt/sources.list.d
  register: check_vic_rep


- name: send shell script
  copy:
    src: ~/openstackope/roles/openstackHV/tasks/repo.sh
    dest: ~/  


- name: Ensure to add repository
  script: /root/openstackope/roles/openstackHV/tasks/repo.sh
  when: "'cloudarchive-victoria.list' not in check_vic_rep.stdout"


- name: apt update
  apt:
    update_cache: yes


- name: apt upgrade
  apt:
    upgrade: yes
