---
- name: hostname config
  block:
  - name: openstackHV set
    import_tasks: HVhostname.yml


- name: kvm config
  block:
  - name: openstackHV set
    import_tasks: HVkvm.yml


- name: repository config
  block:
  - name: repository set
    import_tasks: HVopenstack_repository.yml


- name: nova config
  block:
  - name: nova set
    import_tasks: HVnova.yml


- name: horizon config
  block:
  - name: horizon set
    import_tasks: HVhorizon.yml
